### ISSUE TITLE
[Bug] MoreDefaultOptions completely unable to find files.

### ISSUE THREAD

**Issue by majix560** [BinaryCrafter/MoreDefaultOptions#1]
MoreDefaultOptions is skipping my set files saying their missing.
I got everything set up correctly...
Or at least it's correct according to the curseforge page.
All of the config files and logs are in the zip archive attached.
[Configury.zip](https://github.com/BinaryCrafter/MoreDefaultOptions/files/610312/Configury.zip)

**Comment by BinaryCrafter** [comment]
It looks like your MoreDefaultOptions folder is in the wrong location. It should be in the config folder, i.e.

    GameDIr/config/moredefaultoptions

not

    GameDir/Moredefaultoptions as it is in your attachment.

I'm pretty sure this is what the problem is, but please get back in touch if I'm mistaken and I'll take another look.

I'll check the instructions on the forge page, and see if I can make it clearer. I'll leave this issue open until I've done that.

**Comment by BinaryCrafter** [comment]
I've updated the documentation on the Curse website, so hopefully this issue should now be resolved. If you still don't think it's clear, please re-open this issue with an explanation, and I'll be happy to correct anything that still isn't clear.

Thanks for reporting this issue.
