### ISSUE TITLE
MoreDefaultOptions isn't running early enough

### ISSUE THREAD

**Issue by majix560** [BinaryCrafter/MoreDefaultOptions#2]
MoreDefaultOptions isn't running early enough in the FML loading process.
As a result, the majority of mods in my pack have already generated their default config before MoreDefaultOptions has a chance to make one for it.
[MoreDefaultOptions Section of fml-client-latest.log](http://pastebin.com/NQ63Bpf6)
[fml-client-latest.log](https://github.com/BinaryCrafter/MoreDefaultOptions/files/620470/fml-client-latest.log.txt)

**Comment by BinaryCrafter** [comment]
Apologies if I'm wrong, but looking at the log file you've provided, I suspect you might be misunderstanding the point of this mod.

Please correct me if I'm wrong however.

This mod is specifically to allow modpack creators to set default **_user_** options, not default _**mod**_ configuration.

Files such as those appearing in you log file are **_mod_** configuration files, and you should just ship them in the config directory directly, you don't need my mod for that.

**_User_** options are files that don't normally exist until the user makes a change to a setting in game (e.g. controls on the pause menu), or for instance the journey map settings by opening the in game GUI.

If as a modpack developer you ship an options.txt (for control options), or files in the /journeymap directory, then every time you update your modpack, and players update, it will overwrite their settings, you'll find your players will get really annoyed and either complain, or look for another modpack.

All my mod does, is allow you to tweak the default user options on first install of the modpack, but not touch them when the pack is updated.

For instance, you can set the default key controls when the pack is first installed, but don't overwrite them when the pack is updated, as the user might have painstakingly updated them to suit their preference or keyboard layout. Same with JourneyMap user configuration can be created the first time the pack installed, you might for instance not like players to be greeted with the default journeymap theme, or you might want to set the map to appear rectangular or on the top left of the screen instead of the top right. The user might decide they don't like your preferred defaults you ship with the pack and change them some more, but by shipping these user settings with my mod, updates to your pack will never overwrite **_user_** settings that they've altered.

Hopefully I've explained that and you can now resolve your issue?

If there's anything you don't understand, or if I'm mistaken, then please post back and re-open this issue, and I'll try my best to help further.

**Comment by TheRandomLabs** [comment]
This issue still exists. For example, since MoreDefaultOptions loads *after* MacroKey, I can't set some default settings for MacroKey because the configuration is already created. A possible resolution could be to set the modid to something like "0000moredefaultoptions".

**Comment by BinaryCrafter** [comment]
@TheRandomLabs Please refer to the above comment I left.

I'm not familiar with the mod, but in general, if you're trying to place a file in the /config/ directory, this mod isn't for you!

This mod is intended to package _user_ configuration files (e.g. options.txt), or other files that are generated as a result of a _user_ changing a configuration option via a mod's GUI (e.g. Journeymap options).

If you want to ship a default configuration mod file (e.g. /config/modnamehere.cfg), then don't use my mod, just ship the file as part of your modpack, you don't need a mod to achieve this!

As I say, I'm not familiar with the mod in question (though I have had a quick look at the source code and description of it), and from what I can gather my mod is not designed to do what you are trying to make it do. If you think I misunderstand, then feel free to reply/reopen and I'll look again.

**Comment by TheRandomLabs** [comment]
I understand what you said above, but there are some mods that actually store *user* configuration files in /config.

**Comment by BinaryCrafter** [comment]
@TheRandomLabs Okay, gotcha, thanks for the clarification. In this case, can't you just ship your preferred defaults for your mod pack in the .cfg file packaged in the config directory?

**Comment by TheRandomLabs** [comment]
Like the JourneyMap configuration, if the user changes it, then the config would be overriden in the next update.

**Comment by gigafunk** [comment]
It seems to not be running early enough to even copy the options.txr.

First thing during bootup a options.txt with only the  mipmap setting in it. This blocks the mod from putting it on from cfg. All my other files copy over just not options, log says its already there. I can delete it and each time, at boot first thing it gets created. Any ideas?
